"""Cotizacion table

Revision ID: 0c8a041933f5
Revises: bc0347001f99
Create Date: 2018-05-22 12:06:54.415574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8a041933f5'
down_revision = 'bc0347001f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('VL', sa.Float(), nullable=True),
    sa.Column('activo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activo_id'], ['activo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cotizacion')
    # ### end Alembic commands ###
