"""empty message

Revision ID: 56ee16539274
Revises: 1960febaa3a7
Create Date: 2018-05-22 15:55:05.568344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ee16539274'
down_revision = '1960febaa3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimiento_activo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('unidades', sa.Float(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('activo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activo_id'], ['activo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimiento_activo')
    # ### end Alembic commands ###
