"""Activos table

Revision ID: afdd6e4cf8b7
Revises: 5c4052ae4edb
Create Date: 2018-05-22 11:56:16.561986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdd6e4cf8b7'
down_revision = '5c4052ae4edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=64), nullable=True),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('descargar', sa.Boolean(), nullable=True),
    sa.Column('clase', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_activos_nombre'), 'activos', ['nombre'], unique=True)
    op.create_index(op.f('ix_activos_ticker'), 'activos', ['ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activos_ticker'), table_name='activos')
    op.drop_index(op.f('ix_activos_nombre'), table_name='activos')
    op.drop_table('activos')
    # ### end Alembic commands ###
