"""Cotizacion table

Revision ID: bc0347001f99
Revises: afdd6e4cf8b7
Create Date: 2018-05-22 12:05:15.402445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0347001f99'
down_revision = 'afdd6e4cf8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=64), nullable=True),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('descargar', sa.Boolean(), nullable=True),
    sa.Column('clase', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_activo_nombre'), 'activo', ['nombre'], unique=True)
    op.create_index(op.f('ix_activo_ticker'), 'activo', ['ticker'], unique=True)
    op.drop_index('ix_activos_nombre', table_name='activos')
    op.drop_index('ix_activos_ticker', table_name='activos')
    op.drop_table('activos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=64), nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=64), nullable=True),
    sa.Column('tipo', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('moneda', sa.VARCHAR(length=3), nullable=True),
    sa.Column('descargar', sa.BOOLEAN(), nullable=True),
    sa.Column('clase', sa.VARCHAR(length=1), nullable=True),
    sa.CheckConstraint('descargar IN (0, 1)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_activos_ticker', 'activos', ['ticker'], unique=1)
    op.create_index('ix_activos_nombre', 'activos', ['nombre'], unique=1)
    op.drop_index(op.f('ix_activo_ticker'), table_name='activo')
    op.drop_index(op.f('ix_activo_nombre'), table_name='activo')
    op.drop_table('activo')
    # ### end Alembic commands ###
